- name: generate-snake-game-from-github-contribution-grid
  uses: Platane/snk@v3.0.0
  with:
    # GitHub user name
    github_user_name: doaaosamak
    # List of files to generate, one file per line. Each output can be customized with options as a query string.
    # Supported query string options:
    # - palette: A preset of color, one of [github, github-dark, github-light]
    # - color_snake: Color of the snake
    # - color_dots: Comma-separated list of dot colors.
    #   The first one is 0 contribution, then it goes from the low contribution to the highest.
    #   Exactly 5 colors are expected.
    # - speed: The speed of the animation, can be set as slow, middle, fast.
    outputs: |
      dark.svg?palette=github-dark&color_snake=#f8d7b7&speed=middle
      light.svg?palette=github-light&color_snake=#f8d7b7&speed=middle
      ocean.gif?palette=github-dark&color_snake=#f8d7b7&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&speed=middle
