- name: generate-snake-game-from-github-contribution-grid
  uses: Platane/snk@v3.0.0
  with:
    # github user name
    github_user_name: your_github_username
    # list of files to generate.
one file per line. Each output can be customized with options as query string.

 supported query string options:

- palette:      A preset of color, one of [github, github-dark, github-light]
- color_snake:  Color of the snake
- color_dots:   Comma separated list of dots color. 
                The first one is 0 contribution, then it goes from the low contribution to the highest.
                Exactly 5 colors are expected.
example:
  outputs: |
    dark.svg?palette=github-dark&color_snake=#efceaf
    light.svg?palette=github-light&color_snake=#efceaf
    ocean.gif?palette=github-dark&color_snake=#efceaf&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
